### ISSUE TITLE
Link on telephone number incorrect

### ISSUE THREAD

**Issue by JoachimS** [Saturate/NSC#7]
The link on the telephone number in the bottom, does not match the number displayed.

**Comment by TakeitEasyAlan** [comment]
Are you looking at wip or :

As ever take it easy, Alan

**Comment by TakeitEasyAlan** [comment]
No, I see this on the frontpage:

<a class="contact__tel" href="tel:+4560477334">+45 7023 3330</a>

Med venlig hilsen

Joachim Schiødtz
Seniorrådgiver, Partner

**Comment by Saturate** [comment]
Fixed, deployed and tested! :-)

**Comment by IsaPentia** [comment]
Juhu. Så skal den bare rulles ud. Flot arbejde
Hvordan tilføjer jeg ting?

De bedste hilsner/Best regards
Isa Lindbæk
Kommunikationskonsulent
+45 5355 7485
[Pentia_logo_black signatur1]
Pentia A/S
Islands Brygge 55
2300 København S

**Comment by Saturate** [comment]
Den er ude :-)

Hvad vil du tilføje, speakers?
